
DROP TABLE IF EXISTS users;
CREATE TABLE users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    sid VARCHAR(255) NOT NULL UNIQUE,
    guid CHAR(36) NOT NULL DEFAULT (UUID()),
    nickname VARCHAR(255) NOT NULL DEFAULT (''),
    name VARCHAR(255) NOT NULL DEFAULT (''),
    picture VARCHAR(255) NOT NULL DEFAULT (''),
    email VARCHAR(255) NOT NULL DEFAULT (''),
    email_verified VARCHAR(6) NOT NULL DEFAULT (false),
    sub VARCHAR(255) NOT NULL DEFAULT (''),
    exp INT NOT NULL DEFAULT 0
);
